version: "3.9"

services:
  ollama:
    image: ollama/ollama:latest      # official image :contentReference[oaicite:0]{index=0}
    container_name: ollama-server
    volumes:
      - ollama-data:/root/.ollama    # cache models between runs
    ports:
      - "11434:11434"                # expose if you want host access
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:11434/ | grep -q models"]
      interval: 30s
      timeout: 5s
      retries: 5

  app:
    build: .                         # uses Dockerfile below
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
    depends_on:
      ollama:
        condition: service_healthy   # wait until Ollama is up
    command: python -m crewai_app.main

volumes:
  ollama-data:
