name: AI Code Review

on:
  pull_request_target:            # safe trigger for forks :contentReference[oaicite:0]{index=0}
    types: [opened, synchronize, reopened]

permissions:                      # let GITHUB_TOKEN write PR comments
  pull-requests: write            # or supply GH_TOKEN as a secret

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # If you want to run Ollama in the runner, uncomment the next two lines
      # - uses: ollama/ollama-action@v1
      # - run: echo "Ollama ready"
      - run: pip install -r requirements.txt
      - run: python -m crewai_app.main ${{ github.event.number }}
        env:
          OLLAMA_BASE_URL: http://localhost:11434     # or your remote host
          GH_TOKEN: ${{ secrets.GH_TOKEN }}           # omit if using default
